services:
  # A Docker web service
  - type: web
    name: Effortlessly Wiki
    env: docker
    repo: https://github.com/jverch/effortlessly-wiki # optional
    region: oregon # optional (defaults to oregon)
    plan: starter # optional (defaults to starter)
    branch: master # optional (defaults to master)
    # dockerCommand: ./webdis.sh # optional (defaults to Dockerfile command)
    numInstances: 1 # optional (defaults to 1)
    healthCheckPath: /
    disk:
      name: wiki_data
      mountPath: /app
      sizeGB: 1 # optional
